; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink

build_flags =
  -I src
  -I $PROJECT_PACKAGES_DIR/framework-stm32cubef1/Middlewares/ST/STM32_USB_Device_Library/Core/Inc
  -I $PROJECT_PACKAGES_DIR/framework-stm32cubef1/Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc

upload_flags =
  -c
  set CPUTAPID 0x2ba01477
  
